services:
  - type: web
    name: mathur-giri-math-portal
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: ADMIN_SECRET_KEY
        value: GOTEGAON_MATH_2026
      - key: JWT_SECRET
        value: mathur_giri_gotegaon_secret_key_2026


